var START=new Date(2026,8,22),END=new Date(2026,10,19),LAUNCH=new Date(2026,10,19),DAY=86400000;
var pages=[["today","🏠","Hoy"],["calendar","📅","Calendario 59 días"],["radar","🚨","Radar GTA VI"],["research","🔎","Investigación"],["pipeline","🎬","Content Pipeline"],["vault","📚","Viral Vault"],["creators","👥","Creadores"],["analytics","📊","Analíticas"],["launch","⚡","Launch Mode"]];
var sources=[
["R★","Rockstar Games · GTA VI","Fuente oficial principal: videos, clips, capturas y novedades.","https://www.rockstargames.com/VI"],
["NW","Rockstar Newswire","Comunicados oficiales y anuncios.","https://www.rockstargames.com/newswire"],
["▶","Rockstar Games · YouTube","Trailers y material audiovisual oficial.","https://www.youtube.com/@RockstarGames"],
["G","Google Trends","Compara GTA 6, GTA VI, Lucía, Jason, Vice City y Rockstar.","https://trends.google.com/"],
["♪","TikTok Creative Center","Hashtags, videos y tendencias en crecimiento.","https://ads.tiktok.com/business/creativecenter/"],
["r/","Reddit · r/GTA6","Detecta dudas, teorías y polémicas. No confirma hechos.","https://www.reddit.com/r/GTA6/"],
["GF","GTAForums","Investigación, discusiones y hallazgos de comunidad.","https://gtaforums.com/"],
["YT","YouTube Search","Comprueba qué temas repiten varios creadores en 24–48 h.","https://www.youtube.com/results?search_query=GTA+6"]
];
var creators=[
["Rockstar Games","Fuente oficial","Primero revisar aquí antes de convertir una noticia en contenido.","https://www.youtube.com/@RockstarGames"],
["Jaruba","Análisis GTA en español","Temas, preguntas, detalles y estructura de investigación.","https://www.youtube.com/results?search_query=Jaruba+GTA+6"],
["DaniRep","Volumen + formatos GTA V","Títulos, frecuencia y formatos históricos de GTA V.","https://www.youtube.com/results?search_query=DaniRep+GTA+V"],
["GTA Series Videos","Guías / secretos","Formatos evergreen: secretos, coleccionables y guías.","https://www.youtube.com/@GTASeriesVideos"],
["TGG","Noticias / guías GTA","Packaging, temas prácticos y velocidad de publicación.","https://www.youtube.com/@TGG_01"],
["DarkViperAU","Experimentos / retos","Mythbusting, experimentos y desafíos.","https://www.youtube.com/@DarkViperAU"],
["TheGrefg","Gaming mainstream","Cómo traducir una noticia a entretenimiento masivo.","https://www.youtube.com/@TheGrefg"],
["elrubiusOMG","Reacción / streaming","Personalidad, reacción y storytelling.","https://www.youtube.com/@elrubiusOMG"]
];
var vault=[
["Misterios","Curiosidad","7 misterios de GTA VI que todavía nadie explica"],
["Secretos","Descubrimiento","10 secretos que Rockstar escondió en GTA VI"],
["Detalles ocultos","Replay value","5 detalles que aparecen menos de 2 segundos"],
["Lugares escondidos","Exploración","Entré a 7 lugares que casi nadie visita"],
["NPC / IA","Experimento","¿Qué pasa si sigo a un NPC durante 1 hora?"],
["Policía","Sistema","Probé hasta dónde te persigue la policía"],
["Vehículos","Comparación","Los 10 autos más rápidos que encontré"],
["Armas","Guía","Dónde encontrar las armas más raras"],
["Bugs","Humor","Los bugs más absurdos de la primera semana"],
["Easter eggs","Nostalgia","Referencias a GTA V que aparecen en GTA VI"],
["Antes vs ahora","Comparación","GTA V vs GTA VI: 12 cambios brutales"],
["Mythbusting","Prueba","Probé 10 mitos de GTA VI"],
["Qué pasa si…","Experimento","¿Qué pasa si…? Episodio 1"],
["Dinero / progreso","Utilidad","La forma más eficiente de ganar dinero al inicio"],
["Mapa","Exploración","Cosas del mapa que no aparecen a simple vista"],
["Retos","Entretenimiento","Intenté sobrevivir 24 horas sin…"],
["Top / ranking","Curación","Las 7 mejores actividades después de la historia"],
["Cosas que no sabías","Microlearning","8 cosas que GTA VI nunca te explica"]
];
var topics=["noticia oficial o actualización","detalle oculto del material oficial","comparación GTA V vs GTA VI","Lucía / Jason / personajes","mapa y mundo abierto","vehículos y físicas","NPC e IA","policía y crimen","misterio o teoría etiquetada","música y ambientación","economía y actividades","pregunta polémica para comentarios"];
var phases=[
["2026-09-22","2026-10-05","FASE 1","Base + pruebas","Construir identidad y probar formatos."],
["2026-10-06","2026-10-19","FASE 2","Encontrar ganadores","Duplicar formatos con mejor respuesta."],
["2026-10-20","2026-11-02","FASE 3","Subir volumen","Aumentar frecuencia con investigación."],
["2026-11-03","2026-11-11","FASE 4","Hype máximo","Cuenta regresiva y preparación técnica."],
["2026-11-12","2026-11-18","FASE 5","Launch Week","Contenido, directos, clips y contingencias."],
["2026-11-19","2026-11-19","FASE 6","LANZAMIENTO","Live + clips + descubrimientos."]
];
function pad(n){return String(n).padStart(2,"0")}function key(d){return d.getFullYear()+"-"+pad(d.getMonth()+1)+"-"+pad(d.getDate())}function fromKey(k){var a=k.split("-").map(Number);return new Date(a[0],a[1]-1,a[2])}function esc(s){return String(s||"").replace(/[&<>"']/g,function(m){return({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"})[m]})}function dayIndex(d){return Math.round((new Date(d.getFullYear(),d.getMonth(),d.getDate())-START)/DAY)}function phase(d){var k=key(d);return phases.find(function(p){return k>=p[0]&&k<=p[1]})||phases[0]}function clamp(d){if(d<START)return START;if(d>END)return END;return d}function fmt(d){return new Intl.DateTimeFormat("es-PE",{weekday:"long",day:"numeric",month:"long"}).format(d)}
var state={page:"today",selected:key(clamp(new Date())),checks:JSON.parse(localStorage.getItem("gta6_checks")||"{}"),radar:JSON.parse(localStorage.getItem("gta6_radar")||"[]"),pipeline:JSON.parse(localStorage.getItem("gta6_pipeline")||"[]"),analytics:JSON.parse(localStorage.getItem("gta6_analytics")||"[]")};
function save(k){localStorage.setItem("gta6_"+k,JSON.stringify(state[k]))}function toast(t){var e=document.getElementById("toast");e.textContent=t;e.classList.add("show");setTimeout(function(){e.classList.remove("show")},1400)}
function plan(d){var i=dayIndex(d),p=phase(d),topic=topics[(i%topics.length+topics.length)%topics.length],n=p[2]=="FASE 1"?2:p[2]=="FASE 2"?2:p[2]=="FASE 3"?3:p[2]=="FASE 4"?3:p[2]=="FASE 5"?4:7,t=[
["research","INVESTIGAR","Radar de 25 minutos","Rockstar → Newswire → YouTube → Trends → TikTok → Reddit. Guarda 3 señales y separa hechos de rumores."],
["short1","PUBLICAR","Pieza #1 · "+topic,"Hook rápido, una sola idea, contexto propio y CTA. Adaptar a TikTok, Shorts, Reels y Facebook."],
["short2","PUBLICAR","Pieza #2 · curiosidad / debate","Responde una duda, muestra un detalle o plantea una pregunta que invite a comentar."],
["vault","ESTUDIAR","Viral Vault · 3 referencias","Guarda 3 videos GTA V: título, hook, miniatura, por qué funcionó y adaptación GTA VI."],
["metrics","MEDIR","Métricas de ayer","Registra views, retención, comentarios y seguidores. Decide qué formato repetir."]
];if(n>=3)t.splice(3,0,["short3","PUBLICAR","Pieza #3 · reacción / comparación","Reacciona a conversación existente o compara una mecánica con GTA V."]);if(n>=4)t.splice(4,0,["short4","PUBLICAR","Pieza #4 · respuesta a comentario","Convierte una pregunta real de audiencia en video."]);if(d.getDay()==0)t.push(["weekly","REVISIÓN","Cierre semanal","Elimina débiles, duplica 2 ganadores y deja 10 ideas listas."]);if(d.getDay()==3)t.push(["profiles","SISTEMA","Auditar perfiles y enlaces","Bio, avatar, enlaces cruzados, branding y CTA hacia YouTube/TikTok."]);if(key(d)=="2026-11-12")t.unshift(["preload","HITO","Activar Launch Week","Revisa plantillas, almacenamiento, directos, clipping y contingencias."]);if(key(d)=="2026-11-18")t.unshift(["eve","HITO","Víspera del lanzamiento","Deja títulos, miniaturas, stream y carpetas preparados. Protege energía."]);if(key(d)=="2026-11-19")t=[["live","LIVE","Abrir transmisión principal","Audio estable, reacción auténtica y grabación horizontal maestra."],["markers","CLIPPING","Marcar momentos en tiempo real","Cada descubrimiento, bug, giro, persecución o reacción fuerte es un clip."],["clips","PUBLICAR","Publicar clips durante el día","Contextualiza y publica rápido; no esperes edición perfecta."],["discover","INVESTIGAR","Primeros descubrimientos","Secretos, IA, policía, físicas, mapa, actividades, armas, bugs y easter eggs."],["long","YOUTUBE","Primer video largo útil","10 cosas que aprendí en mis primeras horas de GTA VI."],["community","COMUNIDAD","Responder dudas","Los comentarios se convierten en las ideas de las siguientes 24 horas."],["backup","SISTEMA","Respaldar material","Duplica grabaciones y organiza por hora/tema."]];return{p:p,topic:topic,n:n,t:t}}
function comp(d){var pl=plan(d),c=state.checks[key(d)]||{},done=pl.t.filter(function(x){return c[x[0]]}).length;return{done:done,total:pl.t.length,pct:Math.round(done/pl.t.length*100)}}function totalProgress(){var done=0,total=0;for(var d=new Date(START);d<=END;d=new Date(d.getTime()+DAY)){var c=comp(d);done+=c.done;total+=c.total}return Math.round(done/total*100)}
function badge(cat){return /LIVE|HITO/.test(cat)?"red":/PUBLICAR|YOUTUBE/.test(cat)?"pink":/INVESTIGAR|ESTUDIAR/.test(cat)?"cyan":/MEDIR|REVISIÓN/.test(cat)?"green":/SISTEMA|CLIPPING/.test(cat)?"yellow":"purple"}
function tasks(d,t){var c=state.checks[key(d)]||{};return '<div class="tasks">'+t.map(function(x){return '<label class="task '+(c[x[0]]?"done":"")+'"><input type="checkbox" data-date="'+key(d)+'" data-check="'+x[0]+'" '+(c[x[0]]?"checked":"")+'><div><span class="badge '+badge(x[1])+'">'+x[1]+'</span><strong>'+esc(x[2])+'</strong><p>'+esc(x[3])+'</p></div></label>'}).join("")+"</div>"}
function sourceHtml(s){return '<div class="source"><div class="logo">'+s[0]+'</div><div class="info"><b>'+esc(s[1])+'</b><small>'+esc(s[2])+'</small></div><a target="_blank" rel="noopener" href="'+s[3]+'">Abrir ↗</a></div>'}
function renderToday(){var d=clamp(new Date()),pl=plan(d),c=comp(d),idx=dayIndex(d)+1;return '<div class="hero"><div class="card"><span class="pill">DÍA '+idx+' / 59</span><h2>Dominar conversación sobre '+esc(pl.topic)+'</h2><p class="muted">Detecta dónde está la atención, publica rápido con contexto propio y convierte cada resultado en aprendizaje.</p><div class="bar"><i style="width:'+c.pct+'%"></i></div><div class="barrow"><span>'+c.done+'/'+c.total+' tareas</span><span>'+c.pct+'%</span></div></div><div class="card"><span class="badge cyan">'+pl.p[2]+'</span><h2 style="font-size:23px">'+pl.p[3]+'</h2><p class="muted">'+pl.p[4]+'</p><span class="pill">'+fmt(d)+'</span></div></div><div class="grid g4 stats"><div class="card stat"><span>Progreso total</span><b>'+totalProgress()+'%</b><small>plan completo</small></div><div class="card stat"><span>Piezas objetivo</span><b>'+pl.n+'</b><small>hoy</small></div><div class="card stat"><span>Pipeline</span><b>'+state.pipeline.length+'</b><small>ideas</small></div><div class="card stat"><span>Radar</span><b>'+state.radar.length+'</b><small>señales</small></div></div><div class="head"><div><h2>Checklist de hoy</h2><p>Marca solo cuando esté terminado.</p></div></div><div class="card">'+tasks(d,pl.t)+'</div><div class="head"><div><h2>Fuentes prioritarias</h2><p>Confirma primero; interpreta después.</p></div></div><div class="grid g2">'+sources.slice(0,4).map(sourceHtml).join("")+'</div>'}
function month(y,m){var f=new Date(y,m,1),last=new Date(y,m+1,0),off=(f.getDay()+6)%7,h="";for(var i=0;i<off;i++)h+='<div class="day off"></div>';for(var n=1;n<=last.getDate();n++){var d=new Date(y,m,n),inside=d>=START&&d<=END,c=inside?comp(d):{pct:0},p=inside?phase(d):null,today=key(d)==key(clamp(new Date()));h+='<div class="day '+(!inside?"off ":"")+(today?"today":"")+'" '+(inside?'data-pick="'+key(d)+'"':"")+'><b>'+n+'</b>'+(inside?'<p>'+p[3]+'</p><div class="mini"><i style="width:'+c.pct+'%"></i></div>':"")+'</div>'}return '<div class="head"><div><h2>'+new Intl.DateTimeFormat("es-PE",{month:"long",year:"numeric"}).format(f)+'</h2></div></div><div class="calendar">'+["Lun","Mar","Mié","Jue","Vie","Sáb","Dom"].map(function(x){return '<div class="dow">'+x+"</div>"}).join("")+h+"</div>"}
function dateDetail(d){var pl=plan(d),c=comp(d);return '<div id="detail" class="card" style="margin-top:15px"><div class="between"><div><h2 style="font-size:17px;margin:0">'+fmt(d)+'</h2><p class="muted" style="font-size:10px">'+pl.p[2]+' · '+pl.p[3]+'</p></div><span class="badge green">'+c.pct+'%</span></div>'+tasks(d,pl.t)+"</div>"}
function renderCalendar(){return '<div class="banner"><span class="pill">22 SEP → 19 NOV</span><h2>59 días de preparación</h2><p class="muted">Haz clic en una fecha para ver la misión exacta. La intensidad aumenta al acercarse el lanzamiento.</p></div>'+month(2026,8)+month(2026,9)+month(2026,10)+dateDetail(fromKey(state.selected))}
function renderResearch(){return '<div class="banner"><h2>Rutina de investigación · 25–40 min</h2><p class="muted">Orden: fuente oficial → tendencia → conversación → creadores. No conviertas ruido en hechos sin verificar.</p></div><div class="head"><div><h2>Fuentes</h2><p>Ábrelas en este orden cada mañana.</p></div></div><div class="grid g2">'+sources.map(sourceHtml).join("")+'</div><div class="head"><div><h2>Búsquedas preparadas</h2></div></div><div class="grid g3">'+["GTA 6 today","GTA VI Rockstar","GTA 6 Lucia","GTA 6 Jason","GTA 6 map","GTA 6 details","GTA 6 secrets","GTA V most viewed secrets","GTA V myths experiments"].map(function(q){return '<div class="card"><span class="badge cyan">SEARCH</span><h3 style="font-size:13px">'+q+'</h3><a class="link" target="_blank" href="https://www.google.com/search?q='+encodeURIComponent(q)+'">Buscar ↗</a></div>'}).join("")+"</div>"}
function renderRadar(){return '<div class="grid g2"><div class="card"><h2 style="font-size:17px">Guardar señal</h2><form id="radarForm" class="form"><input name="title" placeholder="Qué está pasando" required><div class="row"><select name="status"><option>CONFIRMADO</option><option>FUENTE FIABLE</option><option>RUMOR</option><option>ESPECULACIÓN</option><option>FALSO</option></select><input name="source" placeholder="Fuente"></div><input name="url" placeholder="URL"><textarea name="note" placeholder="Ángulo de contenido"></textarea><button class="btn primary">Guardar</button></form></div><div class="card"><h2 style="font-size:17px">Regla editorial</h2><p class="muted">CONFIRMADO = fuente oficial. RUMOR = decirlo explícitamente. ESPECULACIÓN = análisis propio, nunca presentarlo como filtración.</p></div></div><div class="head"><div><h2>Señales guardadas</h2><p>'+state.radar.length+' elementos.</p></div></div>'+(state.radar.length?state.radar.map(function(r,i){return '<div class="radar"><div class="between"><span class="badge '+(r.status=="CONFIRMADO"?"green":r.status=="FALSO"?"red":r.status=="RUMOR"?"yellow":"purple")+'">'+esc(r.status)+'</span><button class="icon" data-del-radar="'+i+'">Eliminar</button></div><h3>'+esc(r.title)+'</h3><p>'+esc(r.note||r.source)+'</p>'+(r.url?'<a class="link" target="_blank" href="'+esc(r.url)+'">Abrir fuente ↗</a>':"")+"</div>"}).join(""):'<div class="empty">Aún no hay señales.</div>')}
function renderCreators(){return '<div class="banner"><h2>Detecta patrones, no copies videos</h2><p class="muted">Observa tema, hook, título, miniatura, velocidad y conversación generada.</p></div><div class="head"><div><h2>Watchlist</h2></div></div><div class="grid g2">'+creators.map(function(c){return '<div class="creator"><div class="logo">'+c[0].slice(0,2).toUpperCase()+'</div><div class="info"><b>'+esc(c[0])+'</b><small>'+esc(c[1])+' · '+esc(c[2])+'</small></div><a target="_blank" href="'+c[3]+'">Ver ↗</a></div>'}).join("")+"</div>"}
function renderVault(){return '<div class="banner"><h2>Viral Vault · GTA V → GTA VI</h2><p class="muted">Copia el formato, no el video. Analiza curiosidad, utilidad, experimentación y entretenimiento.</p></div><div class="head"><div><h2>Formatos para estudiar</h2><p>'+vault.length+' familias.</p></div></div><div class="vault">'+vault.map(function(v){return '<div class="card"><span class="badge purple">'+v[1]+'</span><h3>'+v[0]+'</h3><p class="muted">Busca referentes GTA V y estudia hook, promesa, ritmo y comentarios.</p><div class="adapt"><b>Adaptación:</b><br>'+v[2]+"</div></div>"}).join("")+"</div>"}
function renderPipeline(){var sts=["Idea","Guion","Grabado","Editado","Publicado"];return '<div class="grid g2"><div class="card"><h2 style="font-size:17px">Nueva pieza</h2><form id="pipeForm" class="form"><input name="title" placeholder="Título / idea" required><div class="row"><select name="platform"><option>Todas</option><option>TikTok</option><option>YouTube</option><option>Instagram</option><option>Facebook</option></select><select name="status">'+sts.map(function(s){return"<option>"+s+"</option>"}).join("")+'</select></div><textarea name="hook" placeholder="Hook / enfoque"></textarea><button class="btn primary">Añadir</button></form></div><div class="card"><h2 style="font-size:17px">Sistema</h2><p class="muted">Una pieza madre → clip master → TikTok + Shorts + Reels + Facebook. Multiplica distribución, no trabajo.</p></div></div><div class="head"><div><h2>Tablero</h2></div></div><div class="board">'+sts.map(function(s){var items=state.pipeline.map(function(x,i){return{x:x,i:i}}).filter(function(o){return o.x.status==s});return '<div class="col"><h3>'+s.toUpperCase()+'</h3>'+(items.length?items.map(function(o){return '<div class="piece"><b>'+esc(o.x.title)+'</b><small>'+esc(o.x.platform)+' · '+esc(o.x.hook)+'</small><div>'+(s!="Publicado"?'<button class="icon" data-next="'+o.i+'">Avanzar →</button> ':"")+'<button class="icon" data-del-pipe="'+o.i+'">✕</button></div></div>'}).join(""):'<div class="empty">Vacío</div>')+"</div>"}).join("")+"</div>"}
function num(n){return new Intl.NumberFormat("es-PE",{notation:+n>9999?"compact":"standard"}).format(+n||0)}function best(){if(!state.analytics.length)return"—";var m={};state.analytics.forEach(function(x){m[x.platform]=(m[x.platform]||0)+(+x.views||0)});return Object.entries(m).sort(function(a,b){return b[1]-a[1]})[0][0]}
function renderAnalytics(){var total=state.analytics.reduce(function(a,x){a.v+=+x.views||0;a.f+=+x.followers||0;return a},{v:0,f:0});return '<div class="grid g4"><div class="card stat"><span>Registros</span><b>'+state.analytics.length+'</b><small>piezas</small></div><div class="card stat"><span>Views</span><b>'+num(total.v)+'</b><small>registradas</small></div><div class="card stat"><span>Follows</span><b>'+num(total.f)+'</b><small>atribuidos</small></div><div class="card stat"><span>Mejor plataforma</span><b style="font-size:17px">'+best()+'</b><small>por views</small></div></div><div class="grid g2" style="margin-top:14px"><div class="card"><h2 style="font-size:17px">Registrar resultado</h2><form id="anaForm" class="form"><div class="row"><input name="date" type="date" value="'+key(clamp(new Date()))+'"><select name="platform"><option>TikTok</option><option>YouTube</option><option>Instagram</option><option>Facebook</option></select></div><input name="title" placeholder="Pieza / tema" required><div class="row"><input name="views" type="number" placeholder="Views"><input name="followers" type="number" placeholder="Seguidores"></div><input name="retention" placeholder="Retención (ej. 72%)"><button class="btn primary">Guardar métricas</button></form></div><div class="card"><h2 style="font-size:17px">Decisiones</h2><p class="muted">Views altas + follows bajos → mejora CTA. Retención alta + pocos views → prueba nuevo hook. Comentarios altos → crea respuestas en video.</p></div></div><div class="head"><div><h2>Historial</h2></div></div>'+(state.analytics.length?'<div class="tablewrap"><table><thead><tr><th>Fecha</th><th>Plataforma</th><th>Pieza</th><th>Views</th><th>Retención</th><th>Follows</th><th></th></tr></thead><tbody>'+state.analytics.map(function(a,i){return '<tr><td>'+esc(a.date)+'</td><td>'+esc(a.platform)+'</td><td>'+esc(a.title)+'</td><td>'+num(a.views)+'</td><td>'+esc(a.retention||"—")+'</td><td>'+num(a.followers)+'</td><td><button class="icon" data-del-ana="'+i+'">✕</button></td></tr>'}).join("")+"</tbody></table></div>":'<div class="empty">Sin métricas todavía.</div>')}
function renderLaunch(){var h='<div class="banner"><span class="badge red">12–19 NOVIEMBRE</span><h2>LAUNCH MODE</h2><p class="muted">Menos perfección y más capturar, contextualizar y publicar rápido. La infraestructura debe estar resuelta antes del 19.</p></div><div class="head"><div><h2>Operación de 8 días</h2></div></div>';for(var d=new Date(2026,10,12);d<=END;d=new Date(d.getTime()+DAY)){var pl=plan(d),c=comp(d);h+='<div class="card" style="margin-bottom:9px"><div class="between"><div><h2 style="font-size:15px;margin:0">'+fmt(d)+'</h2><p class="muted" style="font-size:10px">'+pl.p[3]+'</p></div><span class="badge green">'+c.pct+'%</span></div>'+tasks(d,pl.t)+"</div>"}return h}
function nav(){document.getElementById("nav").innerHTML=pages.map(function(p){return '<button data-page="'+p[0]+'" class="'+(state.page==p[0]?"on":"")+'">'+p[1]+" &nbsp;"+p[2]+"</button>"}).join("");document.querySelectorAll("[data-page]").forEach(function(b){b.onclick=function(){state.page=b.dataset.page;document.getElementById("side").classList.remove("open");render()}})}
function countdown(){var n=new Date(),ms=LAUNCH-n,e=document.getElementById("count");if(ms<=0)e.innerHTML="<b>LANZAMIENTO</b><span>GTA VI</span>";else e.innerHTML="<b>"+Math.ceil(ms/DAY)+' días</b><span>hasta GTA VI</span>'}
function render(){nav();var title=pages.find(function(p){return p[0]==state.page})[2];document.getElementById("title").textContent=title;var map={today:renderToday,calendar:renderCalendar,radar:renderRadar,research:renderResearch,pipeline:renderPipeline,vault:renderVault,creators:renderCreators,analytics:renderAnalytics,launch:renderLaunch};document.getElementById("app").innerHTML=map[state.page]();bind();countdown()}
function bind(){document.querySelectorAll("[data-check]").forEach(function(i){i.onchange=function(){var d=i.dataset.date,id=i.dataset.check;state.checks[d]=state.checks[d]||{};state.checks[d][id]=i.checked;save("checks");render()}});document.querySelectorAll("[data-pick]").forEach(function(e){e.onclick=function(){state.selected=e.dataset.pick;document.getElementById("detail").outerHTML=dateDetail(fromKey(state.selected));bind();setTimeout(function(){document.getElementById("detail").scrollIntoView({behavior:"smooth",block:"center"})},20)}});var r=document.getElementById("radarForm");if(r)r.onsubmit=function(e){e.preventDefault();state.radar.unshift(Object.fromEntries(new FormData(r)));save("radar");toast("Guardado en Radar");render()};document.querySelectorAll("[data-del-radar]").forEach(function(b){b.onclick=function(){state.radar.splice(+b.dataset.delRadar,1);save("radar");render()}});var p=document.getElementById("pipeForm");if(p)p.onsubmit=function(e){e.preventDefault();state.pipeline.unshift(Object.fromEntries(new FormData(p)));save("pipeline");toast("Pieza añadida");render()};document.querySelectorAll("[data-del-pipe]").forEach(function(b){b.onclick=function(){state.pipeline.splice(+b.dataset.delPipe,1);save("pipeline");render()}});document.querySelectorAll("[data-next]").forEach(function(b){b.onclick=function(){var i=+b.dataset.next,s=["Idea","Guion","Grabado","Editado","Publicado"],n=Math.min(s.indexOf(state.pipeline[i].status)+1,4);state.pipeline[i].status=s[n];save("pipeline");render()}});var a=document.getElementById("anaForm");if(a)a.onsubmit=function(e){e.preventDefault();state.analytics.unshift(Object.fromEntries(new FormData(a)));save("analytics");toast("Métricas guardadas");render()};document.querySelectorAll("[data-del-ana]").forEach(function(b){b.onclick=function(){state.analytics.splice(+b.dataset.delAna,1);save("analytics");render()}})}
document.getElementById("menu").onclick=function(){document.getElementById("side").classList.toggle("open")};render();setInterval(countdown,60000);